# Setup
title:               JZL
tagline:             ''
description:         'Purposefully left vague'
url:                 https://www.jeffreylou.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jeff Lou
  email:             jeffzlou@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
